export const VERIFICATION_TOKEN_PURPOSE = {
    DEATH_VERIFICATION: "DEATH_VERIFICATION",
};

export const VERIFICATION_TOKEN_PURPOSE_VALUES =
    Object.values(
        VERIFICATION_TOKEN_PURPOSE
    );